<definition>
	<command name="assertTextEquals">
		<case locator-key1="SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertTextNoWaitForText" value1="Your request processed successfully." />
		</case>
	</command>
</definition>