buildscript {
	apply from: "build-buildscript.gradle", to: buildscript
}

apply plugin: "com.liferay.settings.plugin"

String testClassGroup = System.getProperty("test.class.group")
String testClassGroupIndex = System.getProperty("test.class.group.index")
String testClassGroups = System.getProperty("test.class.groups")

if (testClassGroup && testClassGroupIndex && testClassGroups) {
	gradle.ext.testClasses = testClassGroup.tokenize(",")
	gradle.ext.testClassGroupIndex = testClassGroupIndex
	gradle.ext.testClassGroups = testClassGroups
}