ci.test.available.suites=\
    relevant,\
    sf

jira.project.keys=\
    APIO,\
    COMMERCE,\
    CLDSVCS,\
    FARO,\
    IDE,\
    LHC,\
    LOOP,\
    LPS,\
    LRAC,\
    LRCI,\
    LRDCOM,\
    LRDOCS,\
    LRIS,\
    LRQA,\
    OAUTH2,\
    RELEASE,\
    SYNC,\
    TR,\
    WCM