/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.portlet.documentlibrary.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.portlet.documentlibrary.model.DLSync;
import com.liferay.portlet.documentlibrary.service.DLSyncLocalServiceUtil;

/**
 * The extended model base implementation for the DLSync service. Represents a row in the &quot;DLSync&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DLSyncImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DLSyncImpl
 * @see com.liferay.portlet.documentlibrary.model.DLSync
 * @generated
 */
public abstract class DLSyncBaseImpl extends DLSyncModelImpl implements DLSync {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a d l sync model instance should use the {@link DLSync} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			DLSyncLocalServiceUtil.addDLSync(this);
		}
		else {
			DLSyncLocalServiceUtil.updateDLSync(this);
		}
	}
}