<definition>
	<command name="assertTextNotEquals">
		<case locator-key1="SITE_LIST">
			<execute function="AssertTextNotEquals#assertNotPartialText" value1="Liferay" />
		</case>
	</command>
</definition>