buildscript {
	repositories {
		if (!Boolean.getBoolean("maven.local.ignore")) {
			mavenLocal()
		}

		maven {
			url System.properties["repository.url"] ?: "https://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public"
		}
	}

	dependencies {
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.defaults", version: "5.3.117"
	}
}

apply plugin: "com.liferay.poshi.runner"
apply plugin: "com.liferay.poshi.runner.resources.defaults"

poshiRunner {
	if (project.hasProperty("poshiRunnerExtProperties")) {
		poshiPropertiesFile = new File(projectDir.parentFile, project.properties["poshiRunnerExtProperties"])
	}

	openCVVersion = "2.4.10-0.10"
	version = "1.0.102"
}

configurations {
	sikuliComplete
}

dependencies {
	["x86", "x86_64"].each {
		sikuliComplete classifier: "linux-${it}", group: "org.bytedeco.javacpp-presets", name: "opencv", version: poshiRunner.openCVVersion
		sikuliComplete classifier: "windows-${it}", group: "org.bytedeco.javacpp-presets", name: "opencv", version: poshiRunner.openCVVersion
	}

	sikuliComplete classifier: "macosx-x86_64", group: "org.bytedeco.javacpp-presets", name: "opencv", version: poshiRunner.openCVVersion
}

poshiRunnerResources {
	baseNameDir "portal", "test/functional/com/liferay/portalweb"
}

repositories {
	if (!Boolean.getBoolean("maven.local.ignore")) {
		mavenLocal()
	}

	maven {
		url System.properties["repository.url"] ?: "https://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public"
	}
}

task updateGradleCache

runPoshi {
	jvmArgs "-Dfile.encoding=UTF-8"
}

updateGradleCache {
	doLast {
		configurations.poshiRunner.resolve()
		configurations.sikuliComplete.resolve()
	}
}
