backup:
    enabled: false
    region: us-west-2
    rules:
        -   retentionDays: 30
            ruleName: daily-backups
            schedule: cron(0 5 * * ? *)
            startWindow: 60
enabled: true