<definition>
	<command name="assertTextEquals">
		<case locator-key1="ANNOUNCEMENTS_ENTRY_ACTION">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
		<case locator-key1="ANNOUNCEMENTS_ENTRY_CONTENT">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>

	<command name="isElementPresent">
		<case locator-key1="ANNOUNCEMENTS_ENTRY_DELETE_LINK">
			<execute function="IsElementPresent#pauseIsElementPresent" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="WHATS_HAPPENING_CONTENT_INPUT_FIELD">
			<execute function="Type#sendKeys" />
		</case>
	</command>
</definition>