buildscript {
	dependencies {
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.defaults", version: "7.0.238"
	}

	repositories {
		mavenLocal()

		File tmpMavenRepositoryDir = file("/opt/dev/projects/github/liferay-portal/.m2-tmp")

		if (tmpMavenRepositoryDir.exists()) {
			maven {
				url tmpMavenRepositoryDir
			}
		}

		maven {
			url "https://repository-cdn.liferay.com/nexus/content/groups/public"
		}
	}
}

apply plugin: "com.liferay.poshi.runner"
apply plugin: "com.liferay.poshi.runner.resources.defaults"
apply plugin: "com.liferay.source.formatter"

task testrayImport (type: JavaExec)

dependencies {
	poshiRunnerResources group: "com.liferay", name: "com.liferay.poshi.runner.resources", version: "latest.release"
}

def getGradleProperties() {
	Properties gradleProperties = new Properties()

	try {
		InputStream inputStream = new FileInputStream("gradle.properties")

		gradleProperties.load(inputStream)

		return gradleProperties
	}
	catch (Exception e) {
		e.printStackTrace()

		throw e
	}
}

poshiRunner {
	if (project.hasProperty("baseDir")) {
		baseDir = project.getProperty("baseDir")
	}

	if (project.hasProperty("testNames")) {
		testNames = project.getProperty("testNames")
	}

	if (project.hasProperty("poshiRunnerVersion")) {
		version = project.getProperty("poshiRunnerVersion")
	}
}

poshiRunnerResources {
	baseName "default"
}

repositories {
	mavenLocal()

	maven {
		url "https://repository-cdn.liferay.com/nexus/content/groups/public"
	}
}

configurations {
	testray
}

dependencies {
	testray group: "com.liferay", name: "com.liferay.jenkins.results.parser", version: "${jenkinsResultsParserVersion}"
}

testrayImport {
	description = 'Import Testray results.'
	group = 'Testray'

	classpath = configurations.testray
	main = "com.liferay.jenkins.results.parser.testray.DXPCloudClientTestrayImporter"
	systemProperties getGradleProperties()
	workingDir = "${projectDir}"
}

webdriverBinaries {
	if (project.hasProperty("chromeDriverVersion")) {
		chromedriver = project.getProperty("chromeDriverVersion")
	}
}