#
# Jenkins
#

	jenkinsResultsParserVersion=1.0.958

#
# Poshi
#

	chromeDriverVersion=86.0.4240.22
	poshiRunnerVersion=1.0.326
	poshiRunnerExtPropertyFileNames=poshi.properties,poshi-ext.properties

#
# Project
#

	baseDir=src/testFunctional/samples/liferay
	projectDir=.

#
# Testray Build
#

	testrayProductVersion=1.x
	testrayProjectName=DXP Cloud Client
	testrayRoutineName=DXP Cloud Client Routine
	testrayTeamName=DXP Cloud Client Team

#
# Testray Case
#

	testrayCasePriority=1
	testrayComponentName=DXP Cloud Client Component

#
# Testray Run
#

	environmentBrowserName=Google Chrome 86
	environmentOperatingSystemName=OSX 12.0.1 64-Bit

#
# Testray Server
#

	testrayLogsURLPath=reports/production/logs
	testrayServerURL=https://testray.liferay.com