/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.portal.model.impl;

import com.liferay.portal.model.OrgGroupPermission;

/**
 * The extended model base implementation for the OrgGroupPermission service. Represents a row in the &quot;OrgGroupPermission&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OrgGroupPermissionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OrgGroupPermissionImpl
 * @see com.liferay.portal.model.OrgGroupPermission
 * @generated
 */
public abstract class OrgGroupPermissionBaseImpl
	extends OrgGroupPermissionModelImpl implements OrgGroupPermission {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a org group permission model instance should use the {@link OrgGroupPermission} interface instead.
	 */
}