/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.portal.model.impl;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.Resource;
import com.liferay.portal.service.ResourceLocalServiceUtil;

/**
 * The extended model base implementation for the Resource service. Represents a row in the &quot;Resource_&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ResourceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ResourceImpl
 * @see com.liferay.portal.model.Resource
 * @generated
 */
public abstract class ResourceBaseImpl extends ResourceModelImpl
	implements Resource {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a resource model instance should use the {@link Resource} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			ResourceLocalServiceUtil.addResource(this);
		}
		else {
			ResourceLocalServiceUtil.updateResource(this);
		}
	}
}