#
# OAuth
#

liferay.oauth.application.external.reference.codes=\
    liferay-object-actions-etc-spring-boot-oauth-application-headless-server,\
    liferay-object-actions-etc-spring-boot-oauth-application-user-agent

liferay.oauth.urls.excludes=\
    /ready,\
    /webhook

#
# Spring Boot
#

spring.jms.listener.auto-startup=false
server.port=58081