buildscript {
	dependencies {
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.defaults", version: "latest.release"
	}

	repositories {
		maven {
			url "https://repository-cdn.liferay.com/nexus/content/groups/public"
		}

		maven {
			url "https://repository.liferay.com/nexus/content/groups/public"
		}
	}
}

apply plugin: "com.liferay.poshi.runner"

dependencies {
	poshiRunnerResources group: "com.liferay", name: "com.liferay.poshi.runner.resources", version: "1.0.15"
	poshiRunnerResources group: "com.liferay.poshi.runner.resources", name: "portal-master", version: "20230117-d08ec14"
}